# Stage 1: Build React app
FROM node:20-alpine AS build
WORKDIR /app
COPY fe/package*.json .
RUN npm install
COPY fe/ .
RUN npm run build

# Stage 2: Serve với Nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
COPY certs/ /etc/nginx/certs/
# Copy images folder
COPY images/ /usr/share/nginx/images/
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]